### ISSUE TITLE
Just by curiosity...

### ISSUE THREAD

**Issue by CarlosLoboxyz** [HeavyRain266/system-config#1]
Hi, i really like you rice, i'm thinking about creating some kind of method for writing slides for school inside vim, i would like to know how do you achieve that in [this image you post](https://github.com/HeavyRain266/system-config/blob/master/nixos/home/screenshots/light.png), the one that says today's talks

**Comment by HeavyRain266** [comment]
Thats just "Goyo" plugin.

**Comment by CarlosLoboxyz** [comment]
How do you achieve having multiple font size? It's that ascii?

**Comment by HeavyRain266** [comment]
I have only one font size.

**Comment by CarlosLoboxyz** [comment]
i mean inside the the "today's talk" window

**Comment by HeavyRain266** [comment]
> i mean inside the the "today's talk" window

Oh, well It's just mpv with episode of Zig Showtime playing.

**Comment by CarlosLoboxyz** [comment]
Really thanks, that's what i was looking for
